CREATE TABLE public.straatnamen AS (
SELECT
		top10_id,
		type_infrastructuur,
		type_weg,
		hoofdverkeersgebruik,
		gescheiden_rijbaan,
		verhardingstype,
		status,
		hoogteniveau,
		verhardingsbreedteklasse,
		verhardingsbreedte,
		aantal_rijstroken,
		fysiek_voorkomen,
		nederlandse_straatnaam,
		friese_straatnaam,
		wegnummer_a_weg,
		wegnummer_n_weg,
		wegnummer_e_weg,
		wegnummer_s_weg,
		afritnummer,
		afritnaam,
		knooppuntnaam,
		brugnaam,
		tunnelnaam,
		opritjanee,
		viscode,
		ST_Transform(shape, 3857) AS geom ,
		ARRAY[6,7,8,9,10,11,12,13,14,15,16,17,18,19] AS zoomlevel 
	FROM fgdb_brt.straatnamen_hoofdwegen
UNION
	SELECT
		top10_id,
		type_infrastructuur,
		type_weg,
		hoofdverkeersgebruik,
		gescheiden_rijbaan,
		verhardingstype,
		status,
		hoogteniveau,
		verhardingsbreedteklasse,
		verhardingsbreedte,
		aantal_rijstroken,
		fysiek_voorkomen,
		nederlandse_straatnaam,
		friese_straatnaam,
		wegnummer_a_weg,
		wegnummer_n_weg,
		wegnummer_e_weg,
		wegnummer_s_weg,
		afritnummer,
		afritnaam,
		knooppuntnaam,
		brugnaam,
		tunnelnaam,
		opritjanee,
		viscode,
		ST_Transform(shape, 3857) AS geom ,
		ARRAY[6,7,8,9,10,11,12,13,14,15,16,17,18,19] AS zoomlevel 
	FROM fgdb_brt.straatnamen_lokale_wegen

UNION
	SELECT
		top10_id,
		type_infrastructuur,
		type_weg,
		hoofdverkeersgebruik,
		gescheiden_rijbaan,
		verhardingstype,
		status,
		hoogteniveau,
		verhardingsbreedteklasse,
		verhardingsbreedte,
		aantal_rijstroken,
		fysiek_voorkomen,
		nederlandse_straatnaam,
		friese_straatnaam,
		wegnummer_a_weg,
		wegnummer_n_weg,
		wegnummer_e_weg,
		wegnummer_s_weg,
		afritnummer,
		afritnaam,
		knooppuntnaam,
		brugnaam,
		tunnelnaam,
		opritjanee,
		viscode,
		ST_Transform(shape, 3857) AS geom ,
		ARRAY[6,7,8,9,10,11,12,13,14,15,16,17,18,19] AS zoomlevel 
	FROM fgdb_brt.straatnamen_overig

UNION
	SELECT
		top10_id,
		type_infrastructuur,
		type_weg,
		hoofdverkeersgebruik,
		gescheiden_rijbaan,
		verhardingstype,
		status,
		hoogteniveau,
		verhardingsbreedteklasse,
		verhardingsbreedte,
		aantal_rijstroken,
		fysiek_voorkomen,
		nederlandse_straatnaam,
		friese_straatnaam,
		wegnummer_a_weg,
		wegnummer_n_weg,
		wegnummer_e_weg,
		wegnummer_s_weg,
		afritnummer,
		afritnaam,
		knooppuntnaam,
		brugnaam,
		tunnelnaam,
		opritjanee,
		viscode,
		ST_Transform(shape, 3857) AS geom ,
		ARRAY[6,7,8,9,10,11,12,13,14,15,16,17,18,19] AS zoomlevel 
	FROM fgdb_brt.straatnamen_regionale_wegen
UNION
	SELECT
		top10_id,
		type_infrastructuur,
		type_weg,
		hoofdverkeersgebruik,
		gescheiden_rijbaan,
		verhardingstype,
		status,
		hoogteniveau,
		verhardingsbreedteklasse,
		verhardingsbreedte,
		aantal_rijstroken,
		fysiek_voorkomen,
		nederlandse_straatnaam,
		friese_straatnaam,
		wegnummer_a_weg,
		wegnummer_n_weg,
		wegnummer_e_weg,
		wegnummer_s_weg,
		afritnummer,
		afritnaam,
		knooppuntnaam,
		brugnaam,
		tunnelnaam,
		opritjanee,
		viscode,
		ST_Transform(shape, 3857) AS geom ,
		ARRAY[6,7,8,9,10,11,12,13,14,15,16,17,18,19] AS zoomlevel 
	FROM fgdb_brt.straatnamen_straat
ORDER BY zoomlevel
);

ALTER TABLE straatnamen ADD COLUMN fid SERIAL PRIMARY KEY;
CREATE INDEX  straatnamen_gix ON public.straatnamen USING gist (geom);
CLUSTER straatnamen USING straatnamen_gix;
